version: '3.8'

services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=AccountDB;User=sa;Password=YourStrong!Passw0rd
    depends_on:
      - mssql
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
